//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     167
#define IDB_L7                          167
#define IDB_BITMAP4                     168
#define IDB_zero                        169
#define IDB_one                         170
#define IDB_two                         171
#define IDB_three                       172
#define IDB_four                        173
#define IDB_five                        174
#define IDB_six                         175
#define IDB_seven                       176
#define IDB_eight                       177
#define IDB_nine                        178
#define IDB_ten                         179
#define IDB_eleven                      180
#define IDB_twelve                      181
#define IDB_thirsteen                   182
#define IDB_BITMAP19                    183
#define IDB_fourteen                    183
#define IBD_dot                         185
#define IDB_dot                         185
#define IDB_DICEONE                     186
#define IDB_DICETWO                     189
#define IDB_DICETHREE                   190
#define IDB_DICEFOUR                    191
#define IDB_DICEFIX                     192
#define IDB_DICEFIVE                    192
#define IDB_DICESIX                     193
#define IDB_BITMAP6                     194
#define IDB_Question                    194
#define IDB_R101                        195
#define IDB_R102                        196
#define IDB_R103                        197
#define IDB_R104                        198
#define IDB_R105                        199
#define IDB_R106                        200
#define IDB_BITMAP13                    201
#define IDB_R107                        201
#define IDB_R108                        202
#define IDB_R109                        203
#define IDB_R110                        204
#define IDB_R111                        205
#define IDB_R112                        206
#define IDB_R113                        207
#define IDB_R114                        208
#define IDB_R115                        209
#define IDB_R116                        210
#define IDB_BITMAP5                     211
#define IDB_CP2                         211
#define IDB_CP3                         212
#define IDB_CP4                         213
#define IDB_P2                          214
#define IDB_P3                          215
#define IDB_P4                          216
#define IDB_R201                        218
#define IDB_R202                        219
#define IDB_R203                        220
#define IDB_R204                        221
#define IDB_R205                        222
#define IDB_R206                        223
#define IDB_R207                        224
#define IDB_R208                        225
#define IDB_R209                        226
#define IDB_R210                        227
#define IDB_R211                        228
#define IDB_R212                        229
#define IDB_R213                        230
#define IDB_R214                        231
#define IDB_R215                        232
#define IDB_R216                        233
#define IDB_R301                        234
#define IDB_R302                        235
#define IDB_R303                        236
#define IDB_R304                        237
#define IDB_R305                        238
#define IDB_R306                        239
#define IDB_R307                        240
#define IDB_R308                        241
#define IDB_R309                        242
#define IDB_R310                        243
#define IDB_R311                        244
#define IDB_R312                        245
#define IDB_R313                        246
#define IDB_R314                        247
#define IDB_R315                        248
#define IDB_R316                        249
#define IDB_R401                        250
#define IDB_R402                        251
#define IDB_R403                        252
#define IDB_R404                        253
#define IDB_R405                        254
#define IDB_R406                        255
#define IDB_R407                        256
#define IDB_R408                        257
#define IDB_R409                        258
#define IDB_R410                        259
#define IDB_R411                        260
#define IDB_R412                        261
#define IDB_R413                        262
#define IDB_R414                        263
#define IDB_R415                        264
#define IDB_BITMAP25                    265
#define IDB_R416                        265
#define IDB_008                         266
#define IDB_005                         267
#define IDB_004                         268
#define IDB_009                         269
#define IDB_001                         270
#define IDB_007                         271
#define IDB_006                         272
#define IDB_003                         273
#define IDB_002                         274
#define IDB_000                         275
#define IDB_btnsell                     276
#define IDB_btnsellc                    277
#define IDB_buy                         278
#define IDB_level1                      279
#define IDB_level1c                     280
#define IDB_level2                      281
#define IDB_level2c                     282
#define IDB_level3                      283
#define IDB_level3c                     284
#define IDB_poor                        285
#define IDB_sell                        286
#define IDB_buytitle                    287
#define IDB_UI                          288
#define IDB_OK                          289
#define IDB_dollar                      290
#define IDB_LAND                        292
#define IDB_HOUSE_1                     293
#define IDB_HOUSE_2                     294
#define IDB_HOUSE_3                     295
#define IDB_cardRandom                  296
#define IDB_draw                        298
#define IDB_store                       299
#define IDB_L1                          302
#define IDB_L1C                         303
#define IDB_L1T                         304
#define IDB_L2                          305
#define IDB_L2C                         306
#define IDB_L2T                         307
#define IDB_L3                          308
#define IDB_L3C                         309
#define IDB_L3T                         310
#define IDB_L4                          311
#define IDB_L4C                         312
#define IDB_L4T                         313
#define IDB_L5                          314
#define IDB_L5C                         315
#define IDB_L5T                         316
#define IDB_L6                          317
#define IDB_L6C                         318
#define IDB_L6T                         319
#define IDB_L7C                         321
#define IDB_L7T                         322
#define IDB_L8                          323
#define IDB_L8C                         324
#define IDB_L8T                         325
#define IDB_L9                          326
#define IDB_L9C                         327
#define IDB_L9T                         328
#define IDB_L10                         329
#define IDB_L10C                        330
#define IDB_L10T                        331
#define IDB_L_BK                        332
#define IDB_L_OK                        333
#define IDB_L_OK_T                      334
#define IDB_open1                       335
#define IDB_open2                       336
#define IDB_open3                       337
#define IDB_open4                       338
#define IDB_open5                       339
#define IDB_open6                       340
#define IDB_open7                       341
#define IDB_open8                       342
#define IDB_open9                       343
#define IDB_open10                      344
#define IDB_L_R1                        345
#define IDB_L_R2                        346
#define IDB_L_R3                        347
#define IDB_L_R4                        348
#define IDB_random1                     349
#define IDB_random2                     350
#define IDB_random3                     351
#define IDB_random4                     352
#define IDB_random5                     353
#define IDB_random6                     354
#define IDB_random7                     355
#define IDB_bag_option                  356
#define IDB_bag_option_choosed          357
#define IDB_lottery_option              358
#define IDB_lottery_option_choosed      359
#define IDB_BITMAP11                    360
#define IDB_menu_BK                     360
#define IDB_Car_1                       362
#define IDB_Car_2                       363
#define IDB_Car_3                       364
#define IDB_Car_4                       365
#define IDB_Car_5                       366
#define IDB_Car6                        367
#define IDB_Car_6                       367
#define IDB_Car_7                       368
#define IDB_Car_8                       369
#define IDB_Car_9                       370
#define IDB_Car_10                      371
#define IDB_Car_11                      372
#define IDB_Car_12                      373
#define IDB_Car_13                      374
#define IDB_Car_14                      375
#define IDB_Car_15                      376
#define IDB_Car_16                      377
#define IDB_bomb1                       378
#define IDB_bomb2                       379
#define IDB_bomb3                       380
#define IDB_bomb4                       381
#define IDB_bomb5                       382
#define IDB_bomb6                       383
#define IDB_bomb7                       384
#define IDB_bomb8                       385
#define IDB_bomb9                       386
#define IDB_bomb10                      387
#define IDB_bomb11                      388
#define IDB_bomb12                      389
#define IDB_bomb13                      390
#define IDB_bomb14                      391
#define IDB_bomb15                      392
#define IDB_bombCard                    394
#define IDB_carCard                     395
#define IDB_stealCard                   396
#define IDB_steal1                      397
#define IDB_steal2                      398
#define IDB_steal3                      399
#define IDB_steal4                      400
#define IDB_steal5                      401
#define IDB_steal6                      402
#define IDB_logo_house                  403
#define IDB_logo_money                  404
#define IDB_bankrupt                    405
#define IDB_win                         406
#define IDB_explain                     407
#define IDB_explainIcon                 408
#define IDB_BITMAP7                     409
#define IDB_INT                         409
#define IDB_BITMAP8                     410
#define IDB_about                       410
#define IDB_BITMAP9                     411
#define IDB_aboutIcon                   411
#define IDB_BITMAP10                    412
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775
#define GREEN                           57664

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        413
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
